# Day 1 — NumPy: Arrays, Operations, Slicing

## Part 1 — Creating Arrays

In [1]:
import numpy as np

In [2]:
#1D array
a = np.array([1,2,3,4,5])
print(a)
print(type(a))
print(a.shape) #(5,) - 5 elements, 1 dimention
print(a.dtype) #int64

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
int64


In [4]:
#2D array
b = np.array([[1,2,3], [4,5,6]])
print(b.shape) #(2,3) - 2 rows, 3 columns

(2, 3)


In [5]:
#Useful shortcuts
print(np.zeros((3,3))) #3x3 matrix of zeros
print(np.ones((2,4))) #2x4 matrix of ones
print(np.arange(0,10,2)) # [0, 2, 4, 6, 8]
print(np.linspace(0,1,5)) # 5 evenly spaced values between 0 and 1.
print(np.random.randint(0, 100, (3,3))) # random 3x3 matrix

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[59 32 71]
 [22 37 75]
 [16 28 10]]


Why this matters for ML: Every dataset, every image, every model input/output is a numpy array under the hood. Pandas, scikit-learn, PyTorch — all built on this.

## Part 2 — Operations

In [6]:
a = np.array([1,2,3,4,5])
b = np.array([10,20,30,40,50])

In [7]:
#Element-wise operations - this is the key difference from python lists
print(a + b) #[11,22,33,44,55]
print(a * b) #[10,40,90,160,250]
print(a ** 2) #[1,4,9,16,25]
print(b/a) #[10.0, 10.0, 10.0, 10.0, 10.0]

[11 22 33 44 55]
[ 10  40  90 160 250]
[ 1  4  9 16 25]
[10. 10. 10. 10. 10.]


In [8]:
#Scaler operations (broadcasting)
print(a + 100) #[101,102,103,104,105]
print(a * 3) #[3,6,9,12,15]

[101 102 103 104 105]
[ 3  6  9 12 15]


In [9]:
#Aggregate functions
print(np.sum(a)) #15
print(np.mean(a)) #3.0
print(np.max(a)) #5
print(np.min(a)) #1
print(np.std(a)) #standard deviation

15
3.0
5
1
1.4142135623730951


In [10]:
#Matrix operations
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])
print(np.dot(A,B)) #matrix multiplication
print(A.T) #transpose

[[19 22]
 [43 50]]
[[1 3]
 [2 4]]


## Part 3 — Slicing & Indexing

In [11]:
a = np.array([10,20,30,40,50])

In [12]:
#Indexing
print(a[0]) #10
print(a[-1]) #50 - last element

10
50


In [14]:
#Slicing [start:stop:step]
print(a[1:4]) #[20,30,40]
print(a[:3]) #[10,20,30]
print(a[::2]) #[10,30,50] - every 2nd element

[20 30 40]
[10 20 30]
[10 30 50]


In [15]:
#2D slicing - critical for ML
m = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(m[0]) #first row: [1,2,3,4]
print(m[:,0]) #first column: [1,5,9]
print(m[0:2, 1:3]) #rows 0-1, columns 1-2: [[2,3], [6,7]]

[1 2 3 4]
[1 5 9]
[[2 3]
 [6 7]]


In [17]:
#Boolean masking - extremely useful
a = np.array([10,20,30,40,50])
mask = a > 25
print(mask) #[False, False, True, True, True]
print(a[mask]) #[30,40,50] - filter by condition
print(a[a>25]) #same thing, shortend

[False False  True  True  True]
[30 40 50]
[30 40 50]


## Part 4 — Mini Exercises

In [18]:
# Exercise 1
# Create a 1D array of numbers 1–20
# Extract only the even numbers using boolean masking

ex1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,16,16,17,18,19,20])
print(ex1[ex1%2==0])

[ 2  4  6  8 10 12 14 16 16 18 20]


In [26]:
# Exercise 2
# Create a 4x4 matrix of random integers between 0 and 50
# Find the max value in each row (hint: np.max with axis=1)
# Find the mean of the entire matrix

ex2 = np.random.randint(0, 50, (4,4))
print(ex2)
print(np.max(ex2[0,:]))
print(np.max(ex2[1,:]))
print(np.max(ex2[2,:]))
print(np.max(ex2[3,:]))
print(np.mean(ex2))

[[20 22 17 15]
 [31 47 48  8]
 [19 28  0  1]
 [ 0 40 28  0]]
22
48
28
40
20.25


In [28]:
# Exercise 3
# Create two arrays: student_scores = [45, 78, 92, 61, 88]
# and passing_mark = 60
# Use boolean masking to find who passed
# Calculate the average score of only the students who passed

student_scores = np.array([45,78,92,61,88])
passing_mark = 60
passed = student_scores[student_scores > passing_mark]
print(passed)
print(np.mean(passed))

[78 92 61 88]
79.75


In [29]:
# Exercise 4 (stretch)
# Create a 3x3 matrix
# Multiply it by its transpose
# What shape is the result?

ex4 = np.array([[1,2,3], [4,5,6], [7,8,9]])
ex4T = ex4.T
mul = np.dot(ex4, ex4T)
print(mul.shape)

(3, 3)


Review of exercises:

Exercise 1 — Small bug 🐛

#wrote:
ex1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,16,16,17,18,19,20])
^^^ 15 is missing, 16 is duplicated

Minor typo but worth catching. The cleaner way to do this anyway:
ex1 = np.arange(1, 21)
print(ex1[ex1 % 2 == 0])
Always use numpy's own tools instead of manually typing arrays.

---

Exercise 2 — Works, but too repetitive

#wrote:
print(np.max(ex2[0,:]))
print(np.max(ex2[1,:]))
print(np.max(ex2[2,:]))
print(np.max(ex2[3,:]))

This works but defeats the point of numpy. If you had 1000 rows you'd be there all day. The one-liner:
print(np.max(ex2, axis=1))  # axis=1 = operate across columns, per row

`axis=0` = down each column, `axis=1` = across each row.

---

Exercise 3 — Perfect ✅
Logic is exactly right. Boolean mask, filter, mean on filtered result. Nothing to change.

---

Exercise 4 — Correct ✅
`(3,3)` is the right answer. A (3×3) dot (3×3) = (3×3).

---

Overall verdict
You're ready for Day 2. The instincts are right, just sharpen up on using numpy's built-in tools instead of manual repetition. That's exactly the kind of thing that stands out in code reviews.

Push the corrected version with `arange` and `axis=1` then come back for Day 2.